# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/wh/Qt/project/vscodetest/hostcomputer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 887)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(340, 10, 851, 811))
        self.groupBox_2.setObjectName("groupBox_2")
        self.create_coordinates = QtWidgets.QTextEdit(self.groupBox_2)
        self.create_coordinates.setGeometry(QtCore.QRect(10, 30, 801, 741))
        self.create_coordinates.setObjectName("create_coordinates")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.groupBox_2)
        self.verticalScrollBar.setGeometry(QtCore.QRect(810, 30, 16, 741))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.horizontalScrollBar = QtWidgets.QScrollBar(self.groupBox_2)
        self.horizontalScrollBar.setGeometry(QtCore.QRect(10, 770, 811, 16))
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 101, 811))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 40, 81, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 80, 81, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(124, 10, 211, 321))
        self.groupBox.setObjectName("groupBox")
        self.baud_select = QtWidgets.QComboBox(self.groupBox)
        self.baud_select.setGeometry(QtCore.QRect(100, 80, 86, 25))
        self.baud_select.setObjectName("baud_select")
        self.baud_select.addItem("")
        self.baud_select.addItem("")
        self.baud_select.addItem("")
        self.baud_select.addItem("")
        self.baud_select.addItem("")
        self.baud_select.addItem("")
        self.baud_select.addItem("")
        self.baud_select.addItem("")
        self.baud_select.addItem("")
        self.baud_select.addItem("")
        self.baud_select.addItem("")
        self.serialport_num = QtWidgets.QLabel(self.groupBox)
        self.serialport_num.setGeometry(QtCore.QRect(10, 40, 51, 31))
        self.serialport_num.setMinimumSize(QtCore.QSize(51, 0))
        self.serialport_num.setObjectName("serialport_num")
        self.serialport_select = QtWidgets.QComboBox(self.groupBox)
        self.serialport_select.setGeometry(QtCore.QRect(100, 40, 86, 25))
        self.serialport_select.setObjectName("serialport_select")
        self.baud_rate = QtWidgets.QLabel(self.groupBox)
        self.baud_rate.setGeometry(QtCore.QRect(10, 80, 67, 17))
        self.baud_rate.setMinimumSize(QtCore.QSize(67, 0))
        self.baud_rate.setObjectName("baud_rate")
        self.stop_digit = QtWidgets.QLabel(self.groupBox)
        self.stop_digit.setGeometry(QtCore.QRect(10, 200, 67, 17))
        self.stop_digit.setMinimumSize(QtCore.QSize(67, 0))
        self.stop_digit.setObjectName("stop_digit")
        self.check_digit = QtWidgets.QLabel(self.groupBox)
        self.check_digit.setGeometry(QtCore.QRect(10, 120, 67, 17))
        self.check_digit.setMinimumSize(QtCore.QSize(67, 0))
        self.check_digit.setObjectName("check_digit")
        self.data_digit = QtWidgets.QLabel(self.groupBox)
        self.data_digit.setGeometry(QtCore.QRect(10, 160, 67, 17))
        self.data_digit.setMinimumSize(QtCore.QSize(67, 0))
        self.data_digit.setObjectName("data_digit")
        self.stop_select = QtWidgets.QComboBox(self.groupBox)
        self.stop_select.setGeometry(QtCore.QRect(100, 200, 86, 25))
        self.stop_select.setObjectName("stop_select")
        self.stop_select.addItem("")
        self.stop_select.addItem("")
        self.stop_select.addItem("")
        self.stop_select.addItem("")
        self.stop_select.addItem("")
        self.check_method = QtWidgets.QComboBox(self.groupBox)
        self.check_method.setGeometry(QtCore.QRect(100, 120, 86, 25))
        self.check_method.setObjectName("check_method")
        self.check_method.addItem("")
        self.check_method.addItem("")
        self.data_select = QtWidgets.QComboBox(self.groupBox)
        self.data_select.setGeometry(QtCore.QRect(100, 160, 86, 25))
        self.data_select.setObjectName("data_select")
        self.data_select.addItem("")
        self.data_select.addItem("")
        self.data_select.addItem("")
        self.data_select.addItem("")
        self.data_select.addItem("")
        self.data_select.addItem("")
        self.data_select.addItem("")
        self.data_select.addItem("")
        self.data_select.addItem("")
        self.data_select.addItem("")
        self.data_select.addItem("")
        self.open_serialport = QtWidgets.QPushButton(self.groupBox)
        self.open_serialport.setGeometry(QtCore.QRect(110, 260, 89, 25))
        self.open_serialport.setObjectName("open_serialport")
        self.update_serialport = QtWidgets.QPushButton(self.groupBox)
        self.update_serialport.setGeometry(QtCore.QRect(10, 260, 89, 25))
        self.update_serialport.setObjectName("update_serialport")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(124, 340, 211, 481))
        self.groupBox_4.setObjectName("groupBox_4")
        self.UWB1_label = QtWidgets.QLabel(self.groupBox_4)
        self.UWB1_label.setGeometry(QtCore.QRect(10, 30, 51, 17))
        self.UWB1_label.setObjectName("UWB1_label")
        self.UWB2_O = QtWidgets.QLabel(self.groupBox_4)
        self.UWB2_O.setGeometry(QtCore.QRect(110, 30, 41, 17))
        self.UWB2_O.setObjectName("UWB2_O")
        self.UWB3_A = QtWidgets.QLabel(self.groupBox_4)
        self.UWB3_A.setGeometry(QtCore.QRect(10, 60, 51, 17))
        self.UWB3_A.setObjectName("UWB3_A")
        self.UWB1_display = QtWidgets.QLineEdit(self.groupBox_4)
        self.UWB1_display.setGeometry(QtCore.QRect(60, 30, 41, 25))
        self.UWB1_display.setObjectName("UWB1_display")
        self.UWB2_display = QtWidgets.QLineEdit(self.groupBox_4)
        self.UWB2_display.setGeometry(QtCore.QRect(160, 30, 41, 25))
        self.UWB2_display.setObjectName("UWB2_display")
        self.UWB3_display = QtWidgets.QLineEdit(self.groupBox_4)
        self.UWB3_display.setGeometry(QtCore.QRect(60, 60, 41, 25))
        self.UWB3_display.setObjectName("UWB3_display")
        self.UWB4_other = QtWidgets.QLabel(self.groupBox_4)
        self.UWB4_other.setGeometry(QtCore.QRect(110, 60, 51, 17))
        self.UWB4_other.setObjectName("UWB4_other")
        self.UWB4_display = QtWidgets.QLineEdit(self.groupBox_4)
        self.UWB4_display.setGeometry(QtCore.QRect(160, 60, 41, 25))
        self.UWB4_display.setObjectName("UWB4_display")
        self.magnetometer_x_1 = QtWidgets.QLabel(self.groupBox_4)
        self.magnetometer_x_1.setGeometry(QtCore.QRect(20, 180, 67, 17))
        self.magnetometer_x_1.setObjectName("magnetometer_x_1")
        self.mag_x_1_display = QtWidgets.QLineEdit(self.groupBox_4)
        self.mag_x_1_display.setGeometry(QtCore.QRect(100, 180, 71, 25))
        self.mag_x_1_display.setObjectName("mag_x_1_display")
        self.magnetometer_y_1 = QtWidgets.QLabel(self.groupBox_4)
        self.magnetometer_y_1.setGeometry(QtCore.QRect(20, 210, 67, 17))
        self.magnetometer_y_1.setObjectName("magnetometer_y_1")
        self.mag_y_1_display = QtWidgets.QLineEdit(self.groupBox_4)
        self.mag_y_1_display.setGeometry(QtCore.QRect(100, 210, 71, 25))
        self.mag_y_1_display.setObjectName("mag_y_1_display")
        self.magnetometer_z_1 = QtWidgets.QLabel(self.groupBox_4)
        self.magnetometer_z_1.setGeometry(QtCore.QRect(20, 240, 67, 17))
        self.magnetometer_z_1.setObjectName("magnetometer_z_1")
        self.mag_z_1_display = QtWidgets.QLineEdit(self.groupBox_4)
        self.mag_z_1_display.setGeometry(QtCore.QRect(100, 240, 71, 25))
        self.mag_z_1_display.setObjectName("mag_z_1_display")
        self.magnetometer_x_2 = QtWidgets.QLabel(self.groupBox_4)
        self.magnetometer_x_2.setGeometry(QtCore.QRect(20, 270, 67, 17))
        self.magnetometer_x_2.setObjectName("magnetometer_x_2")
        self.magnetometer_z_2 = QtWidgets.QLabel(self.groupBox_4)
        self.magnetometer_z_2.setGeometry(QtCore.QRect(20, 330, 67, 17))
        self.magnetometer_z_2.setObjectName("magnetometer_z_2")
        self.magnetometer_y_2 = QtWidgets.QLabel(self.groupBox_4)
        self.magnetometer_y_2.setGeometry(QtCore.QRect(20, 300, 67, 17))
        self.magnetometer_y_2.setObjectName("magnetometer_y_2")
        self.groy_x_display = QtWidgets.QLineEdit(self.groupBox_4)
        self.groy_x_display.setGeometry(QtCore.QRect(100, 360, 71, 25))
        self.groy_x_display.setObjectName("groy_x_display")
        self.groy_y_display = QtWidgets.QLineEdit(self.groupBox_4)
        self.groy_y_display.setGeometry(QtCore.QRect(100, 390, 71, 25))
        self.groy_y_display.setObjectName("groy_y_display")
        self.mag_y_2_display = QtWidgets.QLineEdit(self.groupBox_4)
        self.mag_y_2_display.setGeometry(QtCore.QRect(100, 300, 71, 25))
        self.mag_y_2_display.setObjectName("mag_y_2_display")
        self.mag_x_2_display = QtWidgets.QLineEdit(self.groupBox_4)
        self.mag_x_2_display.setGeometry(QtCore.QRect(100, 270, 71, 25))
        self.mag_x_2_display.setObjectName("mag_x_2_display")
        self.groy_z_display = QtWidgets.QLineEdit(self.groupBox_4)
        self.groy_z_display.setGeometry(QtCore.QRect(100, 420, 71, 25))
        self.groy_z_display.setObjectName("groy_z_display")
        self.mag_z_2_display = QtWidgets.QLineEdit(self.groupBox_4)
        self.mag_z_2_display.setGeometry(QtCore.QRect(100, 330, 71, 25))
        self.mag_z_2_display.setObjectName("mag_z_2_display")
        self.gyroscope_x = QtWidgets.QLabel(self.groupBox_4)
        self.gyroscope_x.setGeometry(QtCore.QRect(20, 360, 67, 17))
        self.gyroscope_x.setObjectName("gyroscope_x")
        self.gyroscope_z = QtWidgets.QLabel(self.groupBox_4)
        self.gyroscope_z.setGeometry(QtCore.QRect(20, 420, 67, 17))
        self.gyroscope_z.setObjectName("gyroscope_z")
        self.gyroscope_y = QtWidgets.QLabel(self.groupBox_4)
        self.gyroscope_y.setGeometry(QtCore.QRect(20, 390, 67, 17))
        self.gyroscope_y.setObjectName("gyroscope_y")
        self.high_display = QtWidgets.QLineEdit(self.groupBox_4)
        self.high_display.setGeometry(QtCore.QRect(60, 90, 41, 25))
        self.high_display.setObjectName("high_display")
        self.sea_level_distance = QtWidgets.QLabel(self.groupBox_4)
        self.sea_level_distance.setGeometry(QtCore.QRect(10, 90, 41, 17))
        self.sea_level_distance.setObjectName("sea_level_distance")
        self.target_y_display = QtWidgets.QLineEdit(self.groupBox_4)
        self.target_y_display.setGeometry(QtCore.QRect(160, 120, 41, 25))
        self.target_y_display.setObjectName("target_y_display")
        self.target_y = QtWidgets.QLabel(self.groupBox_4)
        self.target_y.setGeometry(QtCore.QRect(110, 120, 41, 17))
        self.target_y.setObjectName("target_y")
        self.target_x_display = QtWidgets.QLineEdit(self.groupBox_4)
        self.target_x_display.setGeometry(QtCore.QRect(60, 120, 41, 25))
        self.target_x_display.setObjectName("target_x_display")
        self.target_x = QtWidgets.QLabel(self.groupBox_4)
        self.target_x.setGeometry(QtCore.QRect(10, 120, 41, 17))
        self.target_x.setObjectName("target_x")
        self.predict_y = QtWidgets.QLabel(self.groupBox_4)
        self.predict_y.setGeometry(QtCore.QRect(110, 150, 41, 17))
        self.predict_y.setObjectName("predict_y")
        self.predict_y_display = QtWidgets.QLineEdit(self.groupBox_4)
        self.predict_y_display.setGeometry(QtCore.QRect(160, 150, 41, 25))
        self.predict_y_display.setObjectName("predict_y_display")
        self.predict_x_display = QtWidgets.QLineEdit(self.groupBox_4)
        self.predict_x_display.setGeometry(QtCore.QRect(60, 150, 41, 25))
        self.predict_x_display.setObjectName("predict_x_display")
        self.predict_x = QtWidgets.QLabel(self.groupBox_4)
        self.predict_x.setGeometry(QtCore.QRect(10, 150, 41, 17))
        self.predict_x.setObjectName("predict_x")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(108, 30, 20, 791))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(328, 30, 20, 791))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(120, 330, 211, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.serialport_select, self.baud_select)
        MainWindow.setTabOrder(self.baud_select, self.check_method)
        MainWindow.setTabOrder(self.check_method, self.data_select)
        MainWindow.setTabOrder(self.data_select, self.stop_select)
        MainWindow.setTabOrder(self.stop_select, self.update_serialport)
        MainWindow.setTabOrder(self.update_serialport, self.open_serialport)
        MainWindow.setTabOrder(self.open_serialport, self.pushButton_3)
        MainWindow.setTabOrder(self.pushButton_3, self.pushButton_4)
        MainWindow.setTabOrder(self.pushButton_4, self.create_coordinates)
        MainWindow.setTabOrder(self.create_coordinates, self.UWB1_display)
        MainWindow.setTabOrder(self.UWB1_display, self.UWB2_display)
        MainWindow.setTabOrder(self.UWB2_display, self.UWB3_display)
        MainWindow.setTabOrder(self.UWB3_display, self.UWB4_display)
        MainWindow.setTabOrder(self.UWB4_display, self.mag_x_1_display)
        MainWindow.setTabOrder(self.mag_x_1_display, self.mag_y_1_display)
        MainWindow.setTabOrder(self.mag_y_1_display, self.mag_z_1_display)
        MainWindow.setTabOrder(self.mag_z_1_display, self.groy_x_display)
        MainWindow.setTabOrder(self.groy_x_display, self.groy_y_display)
        MainWindow.setTabOrder(self.groy_y_display, self.mag_y_2_display)
        MainWindow.setTabOrder(self.mag_y_2_display, self.mag_x_2_display)
        MainWindow.setTabOrder(self.mag_x_2_display, self.groy_z_display)
        MainWindow.setTabOrder(self.groy_z_display, self.mag_z_2_display)
        MainWindow.setTabOrder(self.mag_z_2_display, self.high_display)
        MainWindow.setTabOrder(self.high_display, self.target_y_display)
        MainWindow.setTabOrder(self.target_y_display, self.target_x_display)
        MainWindow.setTabOrder(self.target_x_display, self.predict_y_display)
        MainWindow.setTabOrder(self.predict_y_display, self.predict_x_display)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "建模"))
        self.groupBox_3.setTitle(_translate("MainWindow", "功能选择"))
        self.pushButton_3.setText(_translate("MainWindow", "串口配置"))
        self.pushButton_4.setText(_translate("MainWindow", "建立坐标系"))
        self.groupBox.setTitle(_translate("MainWindow", "串口配置"))
        self.baud_select.setItemText(0, _translate("MainWindow", "2400"))
        self.baud_select.setItemText(1, _translate("MainWindow", "4800"))
        self.baud_select.setItemText(2, _translate("MainWindow", "9600"))
        self.baud_select.setItemText(3, _translate("MainWindow", "19200"))
        self.baud_select.setItemText(4, _translate("MainWindow", "98400"))
        self.baud_select.setItemText(5, _translate("MainWindow", "57600"))
        self.baud_select.setItemText(6, _translate("MainWindow", "115200"))
        self.baud_select.setItemText(7, _translate("MainWindow", "230400"))
        self.baud_select.setItemText(8, _translate("MainWindow", "460800"))
        self.baud_select.setItemText(9, _translate("MainWindow", "500000"))
        self.baud_select.setItemText(10, _translate("MainWindow", "576000"))
        self.serialport_num.setText(_translate("MainWindow", "串口号"))
        self.baud_rate.setText(_translate("MainWindow", "波特率"))
        self.stop_digit.setText(_translate("MainWindow", "停止位"))
        self.check_digit.setText(_translate("MainWindow", "校验位"))
        self.data_digit.setText(_translate("MainWindow", "数据位"))
        self.stop_select.setItemText(0, _translate("MainWindow", "0"))
        self.stop_select.setItemText(1, _translate("MainWindow", "0.5"))
        self.stop_select.setItemText(2, _translate("MainWindow", "1"))
        self.stop_select.setItemText(3, _translate("MainWindow", "1.5"))
        self.stop_select.setItemText(4, _translate("MainWindow", "2"))
        self.check_method.setItemText(0, _translate("MainWindow", "奇校验"))
        self.check_method.setItemText(1, _translate("MainWindow", "偶校验"))
        self.data_select.setItemText(0, _translate("MainWindow", "0"))
        self.data_select.setItemText(1, _translate("MainWindow", "1"))
        self.data_select.setItemText(2, _translate("MainWindow", "2"))
        self.data_select.setItemText(3, _translate("MainWindow", "3"))
        self.data_select.setItemText(4, _translate("MainWindow", "4"))
        self.data_select.setItemText(5, _translate("MainWindow", "5"))
        self.data_select.setItemText(6, _translate("MainWindow", "6"))
        self.data_select.setItemText(7, _translate("MainWindow", "7"))
        self.data_select.setItemText(8, _translate("MainWindow", "8"))
        self.data_select.setItemText(9, _translate("MainWindow", "9"))
        self.data_select.setItemText(10, _translate("MainWindow", "10"))
        self.open_serialport.setText(_translate("MainWindow", "打开"))
        self.update_serialport.setText(_translate("MainWindow", "刷新串口"))
        self.groupBox_4.setTitle(_translate("MainWindow", "参数"))
        self.UWB1_label.setText(_translate("MainWindow", "UWB1"))
        self.UWB2_O.setText(_translate("MainWindow", "UWB2"))
        self.UWB3_A.setText(_translate("MainWindow", "UWB3"))
        self.UWB4_other.setText(_translate("MainWindow", "UWB4"))
        self.magnetometer_x_1.setText(_translate("MainWindow", "Mag_x_1"))
        self.magnetometer_y_1.setText(_translate("MainWindow", "Mag_y_1"))
        self.magnetometer_z_1.setText(_translate("MainWindow", "Mag_z_1"))
        self.magnetometer_x_2.setText(_translate("MainWindow", "Mag_x_2"))
        self.magnetometer_z_2.setText(_translate("MainWindow", "Mag_z_2"))
        self.magnetometer_y_2.setText(_translate("MainWindow", "Mag_y_2"))
        self.gyroscope_x.setText(_translate("MainWindow", "Gryo_x"))
        self.gyroscope_z.setText(_translate("MainWindow", "Gryo_z"))
        self.gyroscope_y.setText(_translate("MainWindow", "Gryo_y"))
        self.sea_level_distance.setText(_translate("MainWindow", "SLD"))
        self.target_y.setText(_translate("MainWindow", "Tar_y"))
        self.target_x.setText(_translate("MainWindow", "Tar_x"))
        self.predict_y.setText(_translate("MainWindow", "pre_y"))
        self.predict_x.setText(_translate("MainWindow", "pre_x"))

